services:
  ai-base:
    build:
      context: .
      dockerfile: Dockerfile.ai-base
    image: ai-base:latest

  ai-jail:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
      dockerfile: Dockerfile
    container_name: ai-jail
    volumes:
      - /home/pedro/workspace:/workspace
      - /home/pedro/.ssh:/ssh-host:ro
      - ./config:/home/dev/.config
      - ~/.ssh/id_ed25519.pub:/home/dev/.ssh/id_ed25519.pub:ro
      - ~/.ssh/config:/home/dev/.ssh/config:ro
      - ~/.ssh/known_hosts:/home/dev/.ssh/known_hosts:ro
    environment:
      GH_TOKEN: ${GH_TOKEN}
      HOME: /home/dev
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
      - "6000:6000"
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
      - "10000:10000"
    stdin_open: true
    tty: true
    restart: unless-stopped

  openclaude:
    build:
      context: .
      dockerfile: Dockerfile.openclaude
    container_name: openclaude
    depends_on:
      - ai-jail
    volumes:
      - ../workspace:/workspace
      - ./config:/home/dev/.config
      - ./openclaude-config:/home/dev/.config/openclaude
      - ~/.ssh/id_ed25519.pub:/home/dev/.ssh/id_ed25519.pub:ro
      - ~/.ssh/config:/home/dev/.ssh/config:ro
      - ~/.ssh/known_hosts:/home/dev/.ssh/known_hosts:ro
    environment:
      HOME: /home/dev
      GH_TOKEN: ${GH_TOKEN}
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      CLAUDE_CODE_USE_OPENAI: "1"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: https://api.openai.com/v1
      OPENAI_MODEL: gpt-5.4-mini
    stdin_open: true
    tty: true
    restart: unless-stopped

  claudecode:
    build:
      context: .
      dockerfile: Dockerfile.claudecode
    container_name: claudecode
    depends_on:
      - ai-jail
    volumes:
      - ../workspace:/workspace
      - ./config:/home/dev/.config
      - ./claudecode-config:/home/dev/.config/claudecode
      - ~/.ssh/id_ed25519.pub:/home/dev/.ssh/id_ed25519.pub:ro
      - ~/.ssh/config:/home/dev/.ssh/config:ro
      - ~/.ssh/known_hosts:/home/dev/.ssh/known_hosts:ro
    environment:
      HOME: /home/dev
      GH_TOKEN: ${GH_TOKEN}
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped

  gemini:
    build:
      context: .
      dockerfile: Dockerfile.geminicli
    container_name: gemini
    depends_on:
      - ai-jail
    volumes:
      - ../workspace:/workspace
      - ./config:/home/dev/.config
      - ./gemini-config:/home/dev/.config/gemini
      - ~/.ssh/id_ed25519.pub:/home/dev/.ssh/id_ed25519.pub:ro
      - ~/.ssh/config:/home/dev/.ssh/config:ro
      - ~/.ssh/known_hosts:/home/dev/.ssh/known_hosts:ro
    environment:
      HOME: /home/dev
      GH_TOKEN: ${GH_TOKEN}
      GIT_USER_NAME: ${GIT_USER_NAME}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER_NAME}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"

volumes:
  mysql_data: